### ISSUE TITLE
VMware triggers reboots 

### ISSUE THREAD

**Issue by perpen** [dnschneid/crouton#1700]
I had no issues getting VirtualBox running, but I am now trying to install VMware Workstation 11 on my Pixel i7 (omg I love this thing), and having a really hard time...

I have been using divx118's kernel packages, then have tried compiling them myself following instructions on the wiki - I always get the same result: when module vmnet is loaded, the box just reboots.
Furthermore I don't have much info after the reboot, pstore remains empty.

I made tons of experiments, and in some cases vmnet would load w/o issues, but I would get the reboot when the vmware app would try configuring the network.
I am getting pretty frustrated and would appreciate a helping hand, or at this stage even just comforting words :)

```yaml
crouton: version 1-20150430123324~master:90ad47ff
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,extension,keyboard,touch,xiwi
host: version 6812.83.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Mon Apr 27 08:42:39 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
